// <auto-generated />
namespace F15Team26.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class shoppingcart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shoppingcart));
        
        string IMigrationMetadata.Id
        {
            get { return "201512012012544_shopping cart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
